### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Inlife233** [Luxusio/ADOFAI-NoStopMod#10]
Because of this mod, when the end of the long press is a mid-spin, you will not be able to click

Appears as:
The long press in T4-X cannot be correctly judged to the end of the long press

**Comment by Luxusio** [comment]
Here's latest alpha version of NoStopMod.
If bug appears again, please reopen this issue. 

https://discord.com/channels/879657537669070848/887863181609959474/994229681614237807
