### ISSUE TITLE
Keyboard Not Working

### ISSUE THREAD

**Issue by LThomas248** [Luxusio/ADOFAI-NoStopMod#7]
When the mod is installed, the keyboard just doesn't work.

Even if the "Key Limiter" option is used, the keyboard does not respond.

The "Key Viewer" of ADOFAI Tweaks works, and tells me which keys have been pressed, however I can't move the orbits.

I'm using the latest version of the game through Steam, and I only have "NoStopMod" installed with "ADOFAI Tweaks".

**Comment by Luxusio** [comment]
Are you using the lastest version of Unity Mod Manager?
If you are not, please update it to latest verison.

If you do, please answer hte following questions.
1. Whitch operation system are you using?
2. Please upload your "Logs" file (ADOFAI > Mod Manager > Logs > Open detailed Log)
