### ISSUE TITLE
Sometimes keys doesnt register

### ISSUE THREAD

**Issue by fangshenghan** [Luxusio/ADOFAI-NoStopMod#8]
While I was playing, sometimes I pressed the key but it didnt register and missed. this has happend for several times and it happens frequently.
I had watched some of the replay footage of my gameplay, I even died in the easiest sections because the key didnt register... like 60bpm straight line...
I have used other keybords and i can confirm its not the keyboard's problem and i can see my keys register on the keyspersecond software.

**Comment by Luxusio** [comment]
I stabilized input mechanism in 1.2.8. 
I used ConcurrentQueue instead of normal Queue. 
Please use 1.2.8.
And please reopen this issue if unusual key ignore happen.

**Comment by fangshenghan** [comment]
thanks



在 2022-06-27 12:27:24，"Kyeong-Jae Kim (김경재)" ***@***.***> 写道：

Closed #8 as completed.
