### ISSUE TITLE
new update (neo cosmos) breaks nostop, refusing any input

### ISSUE THREAD

**Issue by c0rruptedhusky** [Luxusio/ADOFAI-NoStopMod#9]
The new DLC of Neo Cosmos has made NoStop unable to work. Whenever I go to activate the program, it activates fine, but gives the message ["AdofaiTweaks mod's key limiter has been disabled by NoStopMod's async input."](https://i.imgur.com/IPL59Le.png) making the planets [freeze](https://i.imgur.com/FBPQlJT.png) until you disable the mod, returning things back to normal. Nothing so far has fixed this issue as far as deleting AdofaiTweaks, deleting NoStop, running NoStop by itself, or whatever else. I use this mod so that the right alt key presses once instead of twice. I would like to continue using this mod, but I cannot until it is able to work with Neo Cosmos.

**Comment by Luxusio** [comment]
Fixed in 1.2.8
